version: '2'

services:
  phpfpm:
    image: php:7.1-fpm-alpine
    volumes:
      - .:/app
  nginx:
    image: nginx:1.11-alpine
    volumes:
      - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/app/web
    ports:
      - "9090:80"
